# Generated by Django 5.2.5 on 2025-08-21 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kutubxonachi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField()),
                ('ish_vaqti', models.TimeField(choices=[('8:00/13:30', '8:00/13:30'), ('13:30/19:00', '13:30/19:00')])),
            ],
        ),
        migrations.CreateModel(
            name='Muallif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('jins', models.CharField(choices=[('ayol', 'Ayol'), ('erkak', 'Erkak')])),
                ('tirik', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('guruh', models.CharField()),
                ('kurs', models.PositiveSmallIntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')])),
            ],
        ),
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField()),
                ('janr', models.CharField()),
                ('sahifa', models.PositiveSmallIntegerField()),
                ('muallif', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.muallif')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olingan_sana', models.DateField(auto_now_add=True)),
                ('qaytarish_sana', models.DateField()),
                ('Admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.kutubxonachi')),
                ('kitob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.kitob')),
                ('talaba', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.talaba')),
            ],
        ),
    ]
