# Generated by Django 5.2.5 on 2025-08-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talaba',
            name='ism',
            field=models.CharField(max_length=355),
        ),
    ]
