# Generated by Django 5.2.5 on 2025-08-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_talaba_ism'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talaba',
            name='kurs',
            field=models.PositiveSmallIntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=1),
        ),
    ]
