# Generated by Django 5.2.5 on 2025-08-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_talaba_kurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='muallif',
            name='kitob_soni',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='muallif',
            name='tugilgan_sana',
            field=models.CharField(default=30),
        ),
        migrations.AlterField(
            model_name='kutubxonachi',
            name='ish_vaqti',
            field=models.CharField(choices=[('8:00/13:30', '8:00/13:30'), ('13:30/19:00', '13:30/19:00')]),
        ),
        migrations.AlterField(
            model_name='talaba',
            name='kurs',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')]),
        ),
    ]
