# Generated by Django 5.2.5 on 2025-09-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_muallif_kitob_soni_muallif_tugilgan_sana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talaba',
            name='kitob_soni',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
